asgi: Pin the committer time zone explicitly
Because we have counting on git.commit to find
the committer identity for us and it naively
believes that any offset it reads from the
default_signature is locale-specific (including
GMT+0 as if we're somewhere in what, the UK
when they're not in daylight savings?), we should
be providing the committer identity explicitly
so that -0000 is consistently passed to both
parameters.

This also means that the local time zone won't
be respected but... I haven't thought of a good
way to let local user configure that.  So it's
the best we can do for now.  (an IANA time zone
path to a zone in "/usr/share/zoneinfo" would
be nice.)

Also -- default_signature CAN die of lookup error
if no Git identity is configured.  (it is a property
and therefore has imaginable side effects....)

root@comp-sci-400-sp-25-ethan--vr01m:/ # git init --bare /tmp/abc.py
Initialized empty Git repository in /tmp/abc.py/
root@comp-sci-400-sp-25-ethan--vr01m:/ # /var/db/dkwk/venv/bin/python3
Python 3.11.14 (main, Nov 27 2025, 01:11:17) [Clang 19.1.7 (https://github.com/llvm/llvm-project.git llvmorg-19.1.7-0-gcd7080 on freebsd14
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygit2
>>> pygit2.Repository('/tmp/abc.py/')
pygit2.Repository('/tmp/abc.py/')
>>> r = _
>>> r.default_signature
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: "config value 'user.name' was not found"

in the case that happens we still can't lose the
audit log -- fall back to something at least.