rc.d: Include /usr/local/bin in PATH, where git(1) lives
deep below the unwound call stack i have observed that:

  File "/var/db/dkwk/venv/lib/python3.11/site-packages/dkwk/push.py", line 74, in push
    run(cmd, env, location, branch)
  File "/var/db/dkwk/venv/lib/python3.11/site-packages/dkwk/push.py", line 80, in run
    proc = subprocess.Popen(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git'

Claude wanted to perform path search from within asgi.py
with shutil.which, though I was pretty sure this was a
PATH problem, since subprocess.Popen works more os.execv
than os.execvp.  Of course, setting PATH explicitly to
the default hard-coded into FreeBSD's /bin/sh seemed to
do the trick.  The error is something else related to my
faulty push URI... but at least it found git to begin
with so yeah! :)